### ISSUE TITLE
Report 4 pieces of discrepancies between `lineref`s and C source files

### ISSUE THREAD

**Issue by lyazj** [mit-pdos/xv6-riscv-book#34]
When I try the following command in the main directory of this project:

    $ rm -rf latex.out; make $(ls *.tex | sed 's/^/latex.out\//g') >/dev/null

I get the four unexpected error lines:

    kernel/fs.c: cannot find pat re.compile('^..if.n.>.0.')
    kernel/fs.c: cannot find pat re.compile('panic')
    kernel/pipe.c: cannot find pat re.compile('myproc..-\\>killed')
    kernel/proc.c: cannot find pat re.compile('DOC: sleeplock0')

Could you please correct the references in your latex files to your C codes to make the impressive book more rigorous?

This check is inspired by spotting an unterminated line on page 95 of the current book:

    and if the write has extended the file, writei must update its size

**Comment by kaashoek** [comment]
thx!
